#!/usr/bin/env python3
"""Procedurally generate skin-toned hand point clouds for the Phase 8 dataset.

We build hands as a union of trimesh primitives — palm box, 4 fingers as
cylinder chains, opposed thumb — pose them by joint-bending the cylinder
chains, sample surface points via :func:`trimesh.sample.sample_surface`, and
write them as ``data/objects/hand_*.npz`` matching the schema used by
:func:`texture_mapping.load_object_library`.

Phase 8 v2: each base pose is multiplied across 6 Fitzpatrick skin tones × 2
chiralities (right / left) for a total of ~120 hand variants. The base pose
list itself is right-handed; left chirality is generated by mirroring the
right-handed mesh about the YZ plane (which also flips the grasp axis sign).

Phase 14 detail upgrade
-----------------------
The point-splat rasterizer (``src/pcl_to_rgbd.py``, ``SPLAT_RADIUS=1`` + a 3×3
morphological close) fills any inter-finger gap narrower than a few pixels, so
the old 8000-point hands with thick, near-touching fingers rendered as a
skin-coloured blob. To make a large near-wire hand read as a *hand with
separated fingers* we:

1. Sample at much higher density (~32k points) and **concentrate** that budget
   on the fingers/thumb (sampled separately from palm/wrist with a per-part
   budget) so thin fingers stay crisp instead of being starved by the
   area-weighted global sampler.
2. Make fingers **thinner** so each finger's splat footprint is a narrow tube.
3. **Fan the fingers wide** (large abduction) on the open/relaxed poses, and add
   dedicated wide-spread poses, so the air gaps between fingertips are several
   world-pixels wide at the Phase-14 grasp scale and survive the splat + close.
   The pose roster is biased toward separated-finger poses (only the fist /
   thumbs-up keep fingers fully closed).

Each hand carries a manifest entry that includes a ``grasp_axis_local`` field
— a unit 3-vector in the hand's local frame pointing along the line a wire
would lay across the closed fist. ``texture_mapping._place_hand_on_wire``
uses it to align the hand to a tangent on the wire skeleton.

Convention
----------
- Local frame: lowest Y at 0 (wrist plane), centred X/Z, longest XYZ extent
  scaled to 1 (consistent with :func:`load_object_library`).
- ``grasp_axis_local`` is the *closed-fingers axis* — a wire grasped by the
  hand should be parallel to this vector and pass through the palm centre.

Usage
-----
    python src/build_hand_objects.py
    python src/build_hand_objects.py --out data/objects --n-points 32000

The script always re-writes the hand_*.npz files (deterministic via a seed
per-pose). It updates ``data/objects/manifest.json`` *additively* — entries
for non-hand objects are kept verbatim; entries with category ``hand`` are
replaced.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import trimesh
import trimesh.creation


# Skin tone palette (BGR uint8). 6 reference points spanning Fitzpatrick I-VI.
SKIN_TONES_BGR: list[tuple[int, int, int]] = [
    (193, 215, 232),   # very light  (≈Fitzpatrick I/II)
    (158, 188, 217),   # light       (≈Fitzpatrick II)
    (124, 159, 198),   # medium-light(≈Fitzpatrick III)
    ( 95, 132, 178),   # medium      (≈Fitzpatrick IV)
    ( 60,  92, 142),   # tan         (≈Fitzpatrick V)
    ( 38,  58,  98),   # dark        (≈Fitzpatrick VI)
]


# Adult-male reference dimensions (will be scaled per-variant in metadata).
PALM_WIDTH = 0.085      # X
PALM_HEIGHT = 0.022     # Y (thickness, palm-to-back)
PALM_LENGTH = 0.085     # Z (wrist-to-knuckles)

# Phase 14: the wrist is a featureless stub that, at its old length (0.055),
# ate ~1/3 of the normalised "longest-extent=1" axis and crushed the fingers to
# a tiny on-screen fraction (→ a blob). Shrink it to a short cuff so the
# fingers/palm dominate the normalised extent and render large enough to
# separate after the splat + 3×3 close.
WRIST_RADIUS_X = 0.020
WRIST_RADIUS_Y = 0.014
WRIST_LENGTH = 0.015

# Phase 14: longer + thinner fingers so each renders as a distinct narrow tube
# (the old radii ~0.009 were ~4 px thick at the grasp scale, so neighbouring
# fingers' 5-px splats merged). Lengths bumped ~25% so fanned fingertips clear
# the splat radius.
FINGER_LENGTHS = {
    "index":  (0.060, 0.035, 0.028),
    "middle": (0.066, 0.040, 0.030),
    "ring":   (0.060, 0.036, 0.028),
    "pinky":  (0.049, 0.029, 0.023),
}
FINGER_RADIUS = {
    "index":  0.0066,
    "middle": 0.0069,
    "ring":   0.0064,
    "pinky":  0.0057,
}
# Knuckle X positions spread wider than v1 (±0.038 vs ±0.030) so the proximal
# phalanges start out separated, then abduction fans the tips further.
FINGER_KNUCKLE_X = {
    "index":  -0.038,
    "middle": -0.013,
    "ring":   +0.014,
    "pinky":  +0.038,
}

THUMB_PHALANGES = (0.046, 0.033, 0.028)
THUMB_RADIUS = 0.0082

# Relative surface-sampling weight per part. Fingers/thumb are tiny in area but
# carry all the "is this a hand?" detail, so we over-sample them ~3× relative to
# their area share. Palm/wrist get the remainder.
FINGER_SAMPLE_WEIGHT = 3.4
THUMB_SAMPLE_WEIGHT = 3.0
PALM_SAMPLE_WEIGHT = 1.0
WRIST_SAMPLE_WEIGHT = 0.55


@dataclass
class FingerPose:
    """Rotation angles in radians applied at the 3 finger joints.

    Convention: positive ``mcp`` flexes the finger toward the palm; positive
    ``pip``/``dip`` continue the curl. ``abduct`` fans the finger sideways
    (about the palm-normal axis), which is what creates inter-finger gaps.
    """
    mcp: float = 0.0
    pip: float = 0.0
    dip: float = 0.0
    abduct: float = 0.0


@dataclass
class ThumbPose:
    cmc_flex: float = 0.0
    cmc_abduct: float = 0.0
    mcp: float = 0.0
    ip: float = 0.0


@dataclass
class HandPose:
    name: str
    description: str
    fingers: dict[str, FingerPose]
    thumb: ThumbPose
    wrist_tilt_x: float = 0.0
    wrist_tilt_y: float = 0.0
    wrist_tilt_z: float = 0.0
    grasp_role: str = "ulnar"  # ulnar = pinky→thumb axis; tangential = z


def _curl(amount: float, abduct: float = 0.0) -> FingerPose:
    return FingerPose(
        mcp=amount * np.deg2rad(85.0),
        pip=amount * np.deg2rad(95.0),
        dip=amount * np.deg2rad(60.0),
        abduct=abduct,
    )


def _all_curl(amount: float, abduct: float = 0.0) -> dict[str, FingerPose]:
    return {n: _curl(amount, abduct) for n in FINGER_LENGTHS}


def _spread(
    index_ab: float, middle_ab: float, ring_ab: float, pinky_ab: float,
    curl: float = 0.06,
) -> dict[str, FingerPose]:
    """Fingers extended and fanned apart by the given abduction angles (deg)."""
    return {
        "index":  _curl(curl, abduct=np.deg2rad(index_ab)),
        "middle": _curl(curl, abduct=np.deg2rad(middle_ab)),
        "ring":   _curl(curl, abduct=np.deg2rad(ring_ab)),
        "pinky":  _curl(curl, abduct=np.deg2rad(pinky_ab)),
    }


# Right-handed base poses. Left-chirality variants are auto-mirrored.
#
# Phase 14: the roster is biased toward SEPARATED-FINGER poses so a randomly
# placed near-wire hand almost always shows distinct fingers. Only ``fist`` and
# ``thumbs_up`` keep fingers fully closed; the partial grasps keep a wide
# abduction fan so even curled fingers stay apart.
HAND_POSES: list[HandPose] = [
    HandPose(
        name="open_palm_up",
        description="Open palm facing up, fingers spread wide.",
        # Strong abduction fan: index +36°, pinky -42° → fingertips clearly
        # separated at the grasp scale.
        fingers=_spread(+36, +12, -14, -42),
        thumb=ThumbPose(cmc_flex=np.deg2rad(10), cmc_abduct=np.deg2rad(60),
                        mcp=np.deg2rad(5), ip=np.deg2rad(6)),
        wrist_tilt_x=np.deg2rad(-90),
        # Phase 14: ULNAR so the wire lays *across* the palm — the fanned
        # fingers are then viewed broadside (separated) on palm-facing rolls,
        # instead of pointing down the wire and foreshortening to a sliver.
        grasp_role="ulnar",
    ),
    HandPose(
        name="fist",
        description="Closed fist with thumb wrapped over fingers.",
        fingers=_all_curl(1.0),
        thumb=ThumbPose(cmc_flex=np.deg2rad(50), cmc_abduct=np.deg2rad(20),
                        mcp=np.deg2rad(40), ip=np.deg2rad(35)),
        grasp_role="ulnar",
    ),
    HandPose(
        name="pointing",
        description="Index extended, others curled.",
        fingers={
            "index":  _curl(0.02, abduct=np.deg2rad(+6)),
            "middle": _curl(0.95),
            "ring":   _curl(0.95),
            "pinky":  _curl(0.95),
        },
        thumb=ThumbPose(cmc_flex=np.deg2rad(45), cmc_abduct=np.deg2rad(12),
                        mcp=np.deg2rad(35), ip=np.deg2rad(25)),
        grasp_role="ulnar",
    ),
    HandPose(
        name="spread_fan",
        description="Fingers extended and maximally fanned (splay).",
        # The hero pose for finger separation: ~28° of fan between neighbours.
        fingers=_spread(+42, +14, -15, -46, curl=0.03),
        thumb=ThumbPose(cmc_flex=np.deg2rad(6), cmc_abduct=np.deg2rad(64),
                        mcp=np.deg2rad(4), ip=np.deg2rad(4)),
        wrist_tilt_x=np.deg2rad(-90),
        # Phase 14: ULNAR (wire across palm) so the wide fan is broadside.
        grasp_role="ulnar",
    ),
    HandPose(
        name="grasp_cylindrical",
        description="Cylindrical grasp; fingers curled but fanned apart.",
        fingers={
            "index":  _curl(0.62, abduct=np.deg2rad(+14)),
            "middle": _curl(0.66, abduct=np.deg2rad(+3)),
            "ring":   _curl(0.66, abduct=np.deg2rad(-9)),
            "pinky":  _curl(0.70, abduct=np.deg2rad(-20)),
        },
        thumb=ThumbPose(cmc_flex=np.deg2rad(30), cmc_abduct=np.deg2rad(45),
                        mcp=np.deg2rad(15), ip=np.deg2rad(20)),
        grasp_role="ulnar",
    ),
    HandPose(
        name="half_open",
        description="Relaxed half-open hand, fingers spread.",
        fingers={
            "index":  _curl(0.28, abduct=np.deg2rad(+16)),
            "middle": _curl(0.32, abduct=np.deg2rad(+3)),
            "ring":   _curl(0.36, abduct=np.deg2rad(-12)),
            "pinky":  _curl(0.46, abduct=np.deg2rad(-26)),
        },
        thumb=ThumbPose(cmc_flex=np.deg2rad(20), cmc_abduct=np.deg2rad(38),
                        mcp=np.deg2rad(15), ip=np.deg2rad(15)),
        # Phase 14: ULNAR (wire across palm) so spread fingers are broadside.
        grasp_role="ulnar",
    ),
    HandPose(
        name="flat_palm_down",
        description="Flat hand, palm down, all fingers extended and spread.",
        fingers=_spread(+34, +11, -13, -40, curl=0.05),
        thumb=ThumbPose(cmc_flex=np.deg2rad(6), cmc_abduct=np.deg2rad(52),
                        mcp=np.deg2rad(4), ip=np.deg2rad(4)),
        wrist_tilt_x=np.deg2rad(+90),
        # Phase 14: ULNAR (wire across palm) so spread fingers are broadside.
        grasp_role="ulnar",
    ),
    HandPose(
        name="wire_pinch",
        description="Thumb-and-index gripping a thin wire-like object.",
        fingers={
            "index":  FingerPose(mcp=np.deg2rad(30), pip=np.deg2rad(60),
                                  dip=np.deg2rad(30), abduct=np.deg2rad(+8)),
            "middle": _curl(0.40, abduct=np.deg2rad(-2)),
            "ring":   _curl(0.45, abduct=np.deg2rad(-14)),
            "pinky":  _curl(0.55, abduct=np.deg2rad(-26)),
        },
        thumb=ThumbPose(cmc_flex=np.deg2rad(40), cmc_abduct=np.deg2rad(35),
                        mcp=np.deg2rad(45), ip=np.deg2rad(50)),
        grasp_role="ulnar",
    ),
    HandPose(
        name="thumbs_up",
        description="Thumb extended skyward; fist with abducted thumb.",
        fingers=_all_curl(1.0),
        thumb=ThumbPose(cmc_flex=np.deg2rad(-5), cmc_abduct=np.deg2rad(60),
                        mcp=np.deg2rad(-5), ip=np.deg2rad(-5)),
        wrist_tilt_z=np.deg2rad(-30),
        grasp_role="ulnar",
    ),
    HandPose(
        name="two_finger_pinch",
        description="Index + middle extended and fanned; chopstick-style.",
        fingers={
            "index":  FingerPose(mcp=np.deg2rad(18), pip=np.deg2rad(30),
                                  dip=np.deg2rad(18),
                                  abduct=np.deg2rad(+16)),
            "middle": FingerPose(mcp=np.deg2rad(22), pip=np.deg2rad(34),
                                  dip=np.deg2rad(18),
                                  abduct=np.deg2rad(-2)),
            "ring":   _curl(0.85, abduct=np.deg2rad(-16)),
            "pinky":  _curl(0.95, abduct=np.deg2rad(-28)),
        },
        thumb=ThumbPose(cmc_flex=np.deg2rad(40), cmc_abduct=np.deg2rad(20),
                        mcp=np.deg2rad(30), ip=np.deg2rad(30)),
        grasp_role="ulnar",
    ),
]


def _palm_mesh() -> trimesh.Trimesh:
    box = trimesh.creation.box(extents=(PALM_WIDTH, PALM_HEIGHT, PALM_LENGTH))
    box.apply_translation((0.0, PALM_HEIGHT / 2.0, 0.0))
    fillet_l = trimesh.creation.cylinder(
        radius=PALM_HEIGHT / 2.0,
        height=PALM_WIDTH,
        sections=12,
    )
    fillet_l.apply_transform(trimesh.transformations.rotation_matrix(
        np.pi / 2.0, [0, 0, 1]))
    fillet_l.apply_translation(
        (0.0, PALM_HEIGHT / 2.0, -PALM_LENGTH / 2.0))
    fillet_r = fillet_l.copy()
    fillet_r.apply_translation((0.0, 0.0, +PALM_LENGTH))
    palm = trimesh.util.concatenate([box, fillet_l, fillet_r])
    return palm


def _wrist_mesh() -> trimesh.Trimesh:
    cyl = trimesh.creation.cylinder(
        radius=WRIST_RADIUS_X,
        height=WRIST_LENGTH,
        sections=14,
    )
    cyl.apply_translation((0.0, PALM_HEIGHT / 2.0,
                           -PALM_LENGTH / 2.0 - WRIST_LENGTH / 2.0))
    S = np.eye(4)
    S[1, 1] = WRIST_RADIUS_Y / WRIST_RADIUS_X
    cyl.apply_transform(S)
    return cyl


def _phalanx_mesh(length: float, radius: float) -> trimesh.Trimesh:
    body = trimesh.creation.cylinder(radius=radius, height=length, sections=12)
    body.apply_translation((0, 0, length / 2.0))
    cap0 = trimesh.creation.icosphere(subdivisions=2, radius=radius)
    cap1 = trimesh.creation.icosphere(subdivisions=2, radius=radius)
    cap1.apply_translation((0, 0, length))
    return trimesh.util.concatenate([body, cap0, cap1])


def _finger_mesh(name: str, pose: FingerPose) -> trimesh.Trimesh:
    p_lens = FINGER_LENGTHS[name]
    radius = FINGER_RADIUS[name]

    parts: list[trimesh.Trimesh] = []
    cur_T = np.eye(4)

    def _rotation(angle: float, axis: list[float]) -> np.ndarray:
        return trimesh.transformations.rotation_matrix(angle, axis)

    cur_T = cur_T @ _rotation(pose.abduct, [0, 1, 0])
    cur_T = cur_T @ _rotation(pose.mcp, [1, 0, 0])
    proximal = _phalanx_mesh(p_lens[0], radius)
    proximal.apply_transform(cur_T)
    parts.append(proximal)

    end_proximal = cur_T @ _translate(0, 0, p_lens[0])
    cur_T = end_proximal @ _rotation(pose.pip, [1, 0, 0])
    intermediate = _phalanx_mesh(p_lens[1], radius * 0.92)
    intermediate.apply_transform(cur_T)
    parts.append(intermediate)

    end_intermediate = cur_T @ _translate(0, 0, p_lens[1])
    cur_T = end_intermediate @ _rotation(pose.dip, [1, 0, 0])
    distal = _phalanx_mesh(p_lens[2], radius * 0.84)
    distal.apply_transform(cur_T)
    parts.append(distal)

    return trimesh.util.concatenate(parts)


def _translate(x: float, y: float, z: float) -> np.ndarray:
    M = np.eye(4)
    M[:3, 3] = (x, y, z)
    return M


def _thumb_mesh(pose: ThumbPose) -> trimesh.Trimesh:
    parts: list[trimesh.Trimesh] = []
    cur_T = np.eye(4)
    rot = trimesh.transformations.rotation_matrix

    cur_T = cur_T @ rot(pose.cmc_abduct, [0, 1, 0])
    cur_T = cur_T @ rot(pose.cmc_flex, [1, 0, 0])

    metacarpal = _phalanx_mesh(THUMB_PHALANGES[0], THUMB_RADIUS)
    metacarpal.apply_transform(cur_T)
    parts.append(metacarpal)

    end0 = cur_T @ _translate(0, 0, THUMB_PHALANGES[0])
    cur_T = end0 @ rot(pose.mcp, [1, 0, 0])
    proximal = _phalanx_mesh(THUMB_PHALANGES[1], THUMB_RADIUS * 0.93)
    proximal.apply_transform(cur_T)
    parts.append(proximal)

    end1 = cur_T @ _translate(0, 0, THUMB_PHALANGES[1])
    cur_T = end1 @ rot(pose.ip, [1, 0, 0])
    distal = _phalanx_mesh(THUMB_PHALANGES[2], THUMB_RADIUS * 0.84)
    distal.apply_transform(cur_T)
    parts.append(distal)

    return trimesh.util.concatenate(parts)


def _build_hand_parts(
    pose: HandPose, chirality: str,
) -> dict[str, trimesh.Trimesh]:
    """Build the posed hand as labelled sub-meshes (before chirality/tilt).

    Returns a dict mapping part name → mesh in the hand's pre-mirror local
    frame. Keys: ``"palm"``, ``"wrist"``, ``"thumb"`` and one per finger.
    """
    parts: dict[str, trimesh.Trimesh] = {}
    parts["palm"] = _palm_mesh()
    parts["wrist"] = _wrist_mesh()

    for name, fpose in pose.fingers.items():
        finger = _finger_mesh(name, fpose)
        knuckle_x = FINGER_KNUCKLE_X[name]
        if chirality == "left":
            knuckle_x = -knuckle_x
        finger.apply_translation(
            (knuckle_x, PALM_HEIGHT / 2.0, +PALM_LENGTH / 2.0))
        parts[name] = finger

    thumb = _thumb_mesh(pose.thumb)
    thumb_base_x = -PALM_WIDTH / 2.0 - 0.005
    if chirality == "left":
        thumb_base_x = -thumb_base_x
    thumb.apply_translation((thumb_base_x, PALM_HEIGHT / 2.0, +PALM_LENGTH / 4.0))
    parts["thumb"] = thumb

    # Common post-transforms (mirror for left chirality, then wrist tilt) are
    # applied identically to every part so the assembly stays consistent.
    rot = trimesh.transformations.rotation_matrix
    post = np.eye(4)
    if pose.wrist_tilt_x:
        post = rot(pose.wrist_tilt_x, [1, 0, 0]) @ post
    if pose.wrist_tilt_y:
        post = rot(pose.wrist_tilt_y, [0, 1, 0]) @ post
    if pose.wrist_tilt_z:
        post = rot(pose.wrist_tilt_z, [0, 0, 1]) @ post
    if chirality == "left":
        post = post @ np.diag([-1.0, 1.0, 1.0, 1.0])

    if not np.allclose(post, np.eye(4)):
        for m in parts.values():
            m.apply_transform(post)
    return parts


def build_hand(pose: HandPose, chirality: str) -> trimesh.Trimesh:
    """Build a posed hand mesh in its local frame (concatenated parts).

    Local frame:
    - origin at wrist centre (Y=0 on the bottom face of the palm).
    - +Z toward fingers, +X toward the radial side (thumb side for right hand),
      +Y toward palm normal (palm faces +Y).
    """
    return trimesh.util.concatenate(list(_build_hand_parts(pose, chirality).values()))


def _vary_skin_bgr(base_bgr: tuple[int, int, int],
                   n: int,
                   rng: np.random.RandomState,
                   noise_scale: float = 8.0) -> np.ndarray:
    base = np.array(base_bgr, dtype=np.int32)[None, :]
    noise = rng.normal(0, noise_scale, size=(n, 3))
    out = np.clip(base + noise, 0, 255).astype(np.uint8)
    return out


def _normalise_local_frame(points: np.ndarray) -> tuple[np.ndarray, dict]:
    pts = points.astype(np.float64).copy()
    y_min = pts[:, 1].min()
    pts[:, 1] -= y_min
    bbox_mid_x = 0.5 * (pts[:, 0].min() + pts[:, 0].max())
    bbox_mid_z = 0.5 * (pts[:, 2].min() + pts[:, 2].max())
    pts[:, 0] -= bbox_mid_x
    pts[:, 2] -= bbox_mid_z
    extent = max(np.ptp(pts[:, 0]), np.ptp(pts[:, 1]), np.ptp(pts[:, 2]))
    scale = 1.0 / extent if extent > 1e-9 else 1.0
    pts *= scale
    return pts, {"y_offset": -y_min, "x_centre": bbox_mid_x,
                 "z_centre": bbox_mid_z, "scale": scale,
                 "natural_size_units": float(extent)}


def _resolve_grasp_axis(role: str, chirality: str) -> np.ndarray:
    if role == "ulnar":
        sign = +1.0 if chirality == "right" else -1.0
        return np.array([sign, 0.0, 0.0])
    if role == "tangential":
        return np.array([0.0, 0.0, 1.0])
    return np.array([1.0, 0.0, 0.0])


# Which part names are fingers (for the per-part sampling budget / colour boost).
_FINGER_NAMES = set(FINGER_LENGTHS.keys())


def _part_sample_weight(name: str) -> float:
    if name in _FINGER_NAMES:
        return FINGER_SAMPLE_WEIGHT
    if name == "thumb":
        return THUMB_SAMPLE_WEIGHT
    if name == "wrist":
        return WRIST_SAMPLE_WEIGHT
    return PALM_SAMPLE_WEIGHT


def _sample_parts(
    parts: dict[str, trimesh.Trimesh],
    n_points: int,
    seed: int,
) -> tuple[np.ndarray, np.ndarray]:
    """Sample ``n_points`` over the labelled parts with a per-part budget.

    Each part's budget is proportional to ``area × _part_sample_weight`` so the
    fingers/thumb get a disproportionate share of points and stay crisp. Returns
    ``(points (M,3), is_finger (M,) bool)`` where ``M`` is close to ``n_points``.
    """
    names = list(parts.keys())
    areas = np.array([max(float(parts[n].area), 1e-9) for n in names])
    weights = np.array([_part_sample_weight(n) for n in names])
    eff = areas * weights
    frac = eff / eff.sum()
    budgets = np.maximum(1, np.round(frac * n_points).astype(int))

    pts_list: list[np.ndarray] = []
    fing_list: list[np.ndarray] = []
    for i, name in enumerate(names):
        k = int(budgets[i])
        if k <= 0:
            continue
        p, _ = trimesh.sample.sample_surface(
            parts[name], k, seed=(int(seed) + 7919 * i) & 0xFFFFFFFF)
        p = np.asarray(p, dtype=np.float64)
        pts_list.append(p)
        is_fing = (name in _FINGER_NAMES) or (name == "thumb")
        fing_list.append(np.full(p.shape[0], is_fing, dtype=bool))

    pts = np.concatenate(pts_list, axis=0)
    is_finger = np.concatenate(fing_list, axis=0)
    return pts, is_finger


def _sample_hand_pcl(pose: HandPose,
                     chirality: str,
                     n_points: int,
                     base_bgr: tuple[int, int, int],
                     seed: int,
                     ) -> tuple[np.ndarray, np.ndarray, dict]:
    rng = np.random.RandomState(seed)
    parts = _build_hand_parts(pose, chirality)
    pts, is_finger = _sample_parts(parts, n_points, seed)

    colours = _vary_skin_bgr(base_bgr, pts.shape[0], rng, noise_scale=10.0)
    # Subtle warmth toward the fingertips (high Z) so distal phalanges read as
    # fingertips, not just tubes.
    z_norm = (pts[:, 2] - pts[:, 2].min()) / max(1e-9,
                                                  pts[:, 2].max() - pts[:, 2].min())
    fingertip_mask = (z_norm > 0.78) & is_finger
    if fingertip_mask.any():
        boost = (z_norm[fingertip_mask] - 0.78) / 0.22
        colours[fingertip_mask, 2] = np.clip(
            colours[fingertip_mask, 2].astype(np.int32) + (boost * 18).astype(np.int32),
            0, 255).astype(np.uint8)

    pts_norm, calib = _normalise_local_frame(pts)

    axis = _resolve_grasp_axis(pose.grasp_role, chirality)
    axis = axis / np.linalg.norm(axis)
    calib["grasp_axis_local"] = axis.tolist()
    return pts_norm, colours, calib


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Procedurally generate hand point clouds for Phase 8.",
    )
    parser.add_argument("--out", type=Path,
                        default=Path("data/objects"),
                        help="Output directory for hand_*.npz + manifest.json")
    parser.add_argument("--n-points", type=int, default=32000)
    parser.add_argument("--seed-base", type=int, default=2026)
    parser.add_argument("--scale-jitter", type=float, default=0.10)
    args = parser.parse_args()

    out_dir: Path = args.out
    out_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = out_dir / "manifest.json"
    if manifest_path.is_file():
        manifest = json.loads(manifest_path.read_text())
    else:
        manifest = {"description": "", "total": 0, "license_summary": "",
                    "objects": []}
    # Drop existing hand entries; we rewrite them.
    manifest["objects"] = [o for o in manifest.get("objects", [])
                           if o.get("category") != "hand"]
    # Wipe stale hand_*.npz files (v1 schema had different naming).
    for stale in out_dir.glob("hand_*.npz"):
        stale.unlink()

    new_entries: list[dict] = []
    written = 0
    for i, pose in enumerate(HAND_POSES):
        for tone_idx, base_bgr in enumerate(SKIN_TONES_BGR):
            for chirality in ("right", "left"):
                slug = f"hand_{pose.name}_t{tone_idx}_{chirality}"
                seed = (args.seed_base
                        + 17 * i
                        + 113 * tone_idx
                        + (1 if chirality == "left" else 0))
                pts, cols, calib = _sample_hand_pcl(
                    pose, chirality,
                    n_points=args.n_points,
                    base_bgr=base_bgr,
                    seed=seed,
                )

                out_path = out_dir / f"{slug}.npz"
                np.savez_compressed(out_path,
                                    points=pts.astype(np.float32),
                                    colors=cols.astype(np.uint8))
                # Phase 14: bump natural scale 0.20→0.30 so a wire-gripping hand
                # at KIAT_P14_NEG_HANDSCALE reads as a *large* hand on screen
                # (the separated fingers need on-screen size to survive the
                # splat). The loader still scales within natural_scale_range,
                # and the Phase-14 lever multiplies that by HANDSCALE.
                natural_scale = 0.30
                scale_lo = natural_scale * (1.0 - args.scale_jitter)
                scale_hi = natural_scale * (1.0 + args.scale_jitter)

                entry = {
                    "slug": slug,
                    "file": f"{slug}.npz",
                    "category": "hand",
                    "description": f"{pose.description} ({chirality} hand, skin tone {tone_idx}).",
                    "source_url": "procedurally generated (src/build_hand_objects.py)",
                    "license": "internal",
                    "source": "procedural",
                    "n_points": int(pts.shape[0]),
                    "natural_scale_units": natural_scale,
                    "natural_scale_range": [round(scale_lo, 4), round(scale_hi, 4)],
                    "skin_tone_bgr": list(base_bgr),
                    "skin_tone_idx": tone_idx,
                    "chirality": chirality,
                    "pose_family": pose.name,
                    "grasp_axis_local": calib["grasp_axis_local"],
                    "grasp_role": pose.grasp_role,
                    "graspable_on_wire": pose.grasp_role == "ulnar",
                }
                new_entries.append(entry)
                written += 1

    manifest["objects"].extend(new_entries)
    manifest["total"] = len(manifest["objects"])
    manifest["description"] = (
        "CC0 mesh-derived PCLs (Phase 4) + procedural hand/gripper/cable PCLs "
        "(Phase 8 v2; hands upgraded to high-detail separated-finger ~32k-point "
        "clouds in Phase 14). All as coloured point clouds in a normalised local "
        "frame (centred X/Z, lowest Y at 0, longest extent = 1)."
    )
    manifest["license_summary"] = (
        "Phase 4 entries: CC0 from Poly Haven. "
        "Phase 8 hand/gripper/cable entries: internal procedural generation."
    )
    manifest_path.write_text(json.dumps(manifest, indent=2))
    print(f"  wrote {written} hand variants  "
          f"({len(HAND_POSES)} poses × {len(SKIN_TONES_BGR)} tones × 2 chiralities)"
          f"  @ ~{args.n_points} pts each")
    print(f"  manifest: {manifest_path}  total entries now: {manifest['total']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
